medArr = {
  "Heart": [
    "Amiloride and Hydrochlorothiazide",
    "Metoprolol",
    "Urokinase",
    "Nesiritide",
    "Amiloride",
    "Bumetanide",
    "Glyceryl Trinitrate",
    "Heparin",
    "Alteplase",
    "Perindopril",
    "Bisoprolol",
    "Warfarin",
    "Ramipril",
    "Thallous Chloride Tl-201 Injection",
    "Methylprednisolone",
    "Valsartan",
    "Furosemide",
    "Felodipine",
    "Disodium Edetate",
    "Dalteparin",
    "Loxaglate",
    "Dofetilide",
    "Candesartan",
    "Torsemide",
    "Adenosine",
    "Streptokinase",
    "Eptifibatide",
    "Erythrityl Tetranitrate",
    "Quinapril",
    "Aspirin",
    "Atenolol",
    "Timolol Ophthalmic",
    "Alpha-linolenic acid",
    "Milrinone",
    "Cilnidipine",
    "Alprostadil",
    "Propranolol",
    "Tenecteplase",
    "Isosorbide Dinitrate and Hydralazine",
    "Lisinopril",
    "Captopril",
    "Enoxaparin",
    "Evening Primrose",
    "Eicosapentaenoic acid",
    "Digoxin",
    "Dopamine",
    "Carvedilol",
    "Eplerenone",
    "Ranolazine",
    "Nitroglycerin Tablets, Capsules and Spray",
    "Clopidogrel",
    "Trandolapril",
    "Amiodarone",
    "Procainamide",
    "Flosequinan",
    "Epinephrine",
    "Ticagrelor",
    "Isoproterenol Inhalation",
    "Dobutamine",
    "Aprotinin",
    "Perflutren Protein-Type A Microspheres"
  ],
  "Cancer": [
    "Sorafenib",
    "Acalabrutinib",
    "Duvelisib",
    "Necitumumab",
    "Finasteride",
    "Irinotecan",
    "Carboplatin",
    "Acebrophylline",
    "Ibuprofen",
    "Lenvatinib",
    "Palbociclib",
    "Levoleucovorin",
    "Octreotide",
    "Vandetanib",
    "Methadone",
    "Vemurafenib Tablet",
    "Lorlatinib",
    "Imiquimod",
    "Regorafenib",
    "Cyproterone Tablet",
    "Leuprolide",
    "Leucovorin",
    "Fentanyl Buccal Soluble Film",
    "Talazoparib",
    "Aclarubicin",
    "Ceritinib",
    "Nicotine",
    "Estradiol",
    "Fluoxymesterone",
    "Alectinib",
    "Ixazomib",
    "Docetaxel",
    "Trastuzumab with Hyaluronidase",
    "Trabectedin",
    "Goserelin",
    "Amsacrine",
    "Alpelisib",
    "Mogamulizumab-kpkc",
    "Tegafur and Uracil",
    "Venetoclax",
    "Burosumab-twza",
    "Erlotinib",
    "Cabazitaxel",
    "Imipramine",
    "Trastuzumab",
    "Doxorubicin",
    "Acetaminophen or Paracetamol",
    "Osimertinib",
    "Azacitidine",
    "Dolutegravir",
    "Progesterone",
    "Ramucirumab",
    "Elotuzumab",
    "Nelarabine",
    "Binimetinib",
    "Pamidronate",
    "Niraparib",
    "Enasidenib",
    "Nimotuzumab",
    "Pentostatin",
    "Abiraterone Acetate",
    "Atezolizumab",
    "Dacarbazine",
    "Plicamycin",
    "Lapatinib",
    "Inotuzumab ozogamicin",
    "Ipilimumab",
    "Estramustine",
    "Human Papillomavirus Quadrivalent",
    "Paclitaxel",
    "Fludarabine",
    "Fulvestrant",
    "Gilteritinib",
    "Crizotinib",
    "Buserelin",
    "Carmustine",
    "Valrubicin",
    "Mitoxantrone",
    "Melphalan",
    "Pemetrexed",
    "Letrozole",
    "Amifostine",
    "Estrogen",
    "Cisplatin",
    "Abarelix",
    "Chromic Phosphate p32",
    "Afatinib",
    "Triptorelin",
    "Polatuzumab",
    "Vincristine",
    "Oxaliplatin",
    "Mitomycin",
    "Margetuximab",
    "Levamisole",
    "Gefitinib",
    "BCG live  - Bacillus Calmette- Guerin",
    "Tramadol",
    "Clofarabine",
    "Avatrombopag",
    "Interferon Alfa  2A",
    "Nizatidine",
    "Fosfestrol",
    "Chlorambucil",
    "Vinflunine",
    "Ivosidenib",
    "Morphine",
    "Idelalisib",
    "Bexarotene",
    "Abacavir Sulfate, Lamivudine and Zidovudine",
    "Daunorubicin",
    "Moxetumomab pasudotox-tdfk",
    "Abacavir Sulfate and Lamivudine",
    "Selumitinib",
    "Cetuximab",
    "Cyclophosphamide",
    "Capromab pendetide",
    "Mechlorethamine",
    "Bleomycin",
    "Drug Sodium Iodide-i-131",
    "Everolimus",
    "Exemestane",
    "Aldesleukin",
    "Etoposide",
    "Capecitabine",
    "Epirubicin",
    "Thyroxine",
    "Ado-trastuzumab Emtansine",
    "Bevacizumab",
    "Pemigatinib",
    "Technetium Tc 99m Depreotide Injection",
    "Fluorouracil",
    "Mitotane",
    "Vindesine",
    "Pembrolizumab",
    "Cyclosporine",
    "Encorafenib",
    "Streptozocin",
    "Panobinostat",
    "Lenograstim",
    "Rituximab",
    "Avelumab",
    "Alendronate",
    "Alemtuzumab",
    "Panitumumab Injection",
    "Dacomitinib",
    "Brigatinib",
    "Thiotepa",
    "Gemcitabine",
    "Filgrastim",
    "Vorinostat",
    "Rucaparib",
    "Vinorelbine Tartrate",
    "Topotecan",
    "Nilutamide",
    "Bicalutamide",
    "Nilotinib",
    "Varenicline",
    "Vismodegib",
    "Floxuridine Injection",
    "Altretamine",
    "Thyrotropin Alfa",
    "Fentanyl Skin Patches",
    "Dactinomycin",
    "Megestrol",
    "Pralsetinib",
    "Relugolix",
    "Temozolomide",
    "Hydroxy Progesterone",
    "Interferon Alpha- Two B",
    "Mesna",
    "Ethinyl Estradiol and Levonorgestrel",
    "Cytarabine",
    "Abemaciclib",
    "Teniposide",
    "Ifosfamide",
    "Belantamab",
    "Larotrectinib",
    "Olaparib",
    "Anastrozole",
    "Degarelix",
    "Thioguanine",
    "Midostaurin",
    "Methotrexate",
    "Mercaptopurine",
    "Lutetium Lu 177 dotatate",
    "Blinatumomab",
    "Histrelin Acetate",
    "Cladribine",
    "Cemiplimab-rwlc",
    "Pexidartinib",
    "Tegafur, Gimeracil, Oteracil",
    "Nivolumab",
    "Busulphan",
    "Flutamide",
    "Trifluridine and Tipiracil",
    "Tamoxifen",
    "Pertuzumab",
    "Ormeloxifene",
    "Fentanyl Sublingual Tablets",
    "Sunitinib",
    "Hexaminolevulinate Hydrochloride",
    "Nintedanib",
    "Cabozantinib",
    "Apalutamide",
    "Medroxyprogesterone",
    "Eribulin mesylate",
    "Bemotrizinol / Bisoctrizole",
    "Vinblastine",
    "Neratinib",
    "Ziv-Aflibercept",
    "Ixabepilone",
    "Denosumab",
    "Levothyroxine",
    "Sipuleucel-T Suspension",
    "Ribociclib",
    "Etynodiol",
    "Triptorelin Pamoate for Injectable Suspension",
    "Axicabtagene Ciloleucel",
    "Asparaginase / Crisantaspase",
    "Brentuximab Vedotin",
    "Cobimetinib",
    "Porfimer Sodium",
    "Lomustine",
    "Enzalutamide",
    "Talimogene laherparepvec"
  ],
  "Skin": [
    "Ozenoxacin",
    "Ampicillin and Sulbactam",
    "Ammonium Lactate",
    "Isoniazid",
    "Hydrocortisone, Neomycin and Polymyxin",
    "Amoxicillin",
    "Sodium Fusidate",
    "Ibuprofen",
    "Omadacycline",
    "Mometasone",
    "Cefazolin",
    "Butenafine",
    "Cidofovir",
    "Apremilast",
    "Imiquimod",
    "Fluocinolone",
    "Insulin",
    "Econazole",
    "Acyclovir",
    "Benzyl benzoate",
    "Ofloxacin",
    "Cefaclor",
    "Isotretinoin",
    "Zinc oxide",
    "Alclometasone",
    "Halcinonide",
    "Hexachlorophene",
    "Valacyclovir",
    "Cetrimide",
    "Cloxacillin",
    "Faropenem",
    "Colchicine",
    "Resorcinol",
    "Mogamulizumab-kpkc",
    "Selenium Sulfide",
    "Retapamulin",
    "Psoralen (PUVA)",
    "Ampicillin",
    "Permethrin",
    "Sodium Hyaluronate",
    "Mecetronium",
    "Naproxen",
    "Methyl Aminolevulinate Hydrochloride",
    "Binimetinib",
    "Hydrocortisone Valerate",
    "Lactic acid",
    "Certolizumab",
    "Guselkumab",
    "Mafenide",
    "Ciprofloxacin",
    "Desoximetasone",
    "Diethylstilbestrol",
    "Hydroxyurea",
    "Dexpanthenol",
    "Hyaluronidase",
    "Azficel-T",
    "Pyrazinamide",
    "Azelaic  Acid",
    "Clindamycin",
    "Desonide",
    "Estrogen",
    "Ertapenem",
    "Cefotaxime",
    "Amcinonide",
    "Oxytetracycline",
    "Tazarotene",
    "Albumin Human",
    "Nafcillin Sodium",
    "Sulfasalazine",
    "Hydroquinone",
    "Nystatin and Triamcinolone",
    "Chlorambucil",
    "Tacrolimus",
    "Metronidazole Topical",
    "Dapsone",
    "Moxifloxacin",
    "Thalidomide",
    "Quinupristin and Dalfopristin",
    "Rifampin",
    "Efalizumab",
    "Ceftazidime",
    "Tildrakizumab-asmn",
    "Formaldehyde",
    "Zinc Pyrithione",
    "Betamethasone Topical",
    "Cefoperazone Sodium Injection",
    "Cyclophosphamide",
    "Adalimumab",
    "Azathioprine",
    "Naftifine Hydrochloride",
    "Povidone Iodine",
    "Clarithromycin",
    "Linezolid",
    "Imipenem and Cilastatin",
    "Cyclosporine",
    "Calcipotriene and Betamethasone Dipropionate",
    "Gabapentin",
    "Encorafenib",
    "Neomycin Topical",
    "Prednisone",
    "Methoxsalen",
    "Biafine",
    "Terbinafine",
    "Dicloxacillin",
    "Cephaloridine",
    "Halobetasol Propionate",
    "Alefacept",
    "Avelumab",
    "Piperazine",
    "Ustekinumab",
    "Fusidic acid",
    "Fluocinonide",
    "Ixekizumab",
    "Flurandrenolide",
    "Fluoxetine",
    "Clofazimine",
    "Pimecrolimus",
    "Risankizumab",
    "Hydrocortisone",
    "Dehydroepiandrosterone",
    "Triamcinolone Topical",
    "Cephalexin",
    "Amorolfine",
    "Amphotericin B",
    "Cefdinir",
    "Fluticasone",
    "Oritavancin",
    "Meropenem",
    "Allantoin",
    "Secukinumab",
    "Methotrexate",
    "Mupirocin",
    "Delafloxacin",
    "Chloroxylenol",
    "Gatifloxacin",
    "Methylprednisolone",
    "Cetirizine",
    "Leflunomide",
    "Cemiplimab-rwlc",
    "Telavancin",
    "Clobetasol Propinate",
    "Methyltestosterone",
    "Diflorasone Diacetate",
    "Sulfamethoxazole",
    "Anthralin",
    "Diclofenac",
    "Ketoconazole",
    "Triamcinolone",
    "Silver Sulfadiazine",
    "Vancomycin",
    "Celecoxib",
    "Golimumab",
    "Alclometasone Dipropionate",
    "Ceftizoxime",
    "Mafenide Acetate",
    "Topical Clarithromycin",
    "Streptomycin",
    "Bifonazole",
    "Bemotrizinol / Bisoctrizole",
    "Infliximab",
    "Brodalumab",
    "Acitretin",
    "Niacin",
    "Dupilumab",
    "Nitrofurazone",
    "Itraconazole",
    "Tigecycline",
    "Dimethicone",
    "Quiniodochlor",
    "Prednicarbate",
    "Calcipotriene",
    "Ethambutol",
    "Pramoxine and Hydrocortisone",
    "Etoricoxib",
    "Luliconazole",
    "Cobimetinib",
    "Indomethacin",
    "Cinchocaine",
    "Fluconazole",
    "Amoxicillin and Clavulanate Potassium"
  ],
  "Kidney": [
    "Thymoglobulin",
    "Paracetamol",
    "Erythropoietin",
    "Metformin",
    "Nitrofurantoin",
    "Ferrous Sulfate - Iron",
    "Ferumoxytol",
    "Trimethoprim",
    "Ferrous Gluconate",
    "Amoxicillin",
    "Pitofenone",
    "Ciprofloxacin",
    "Tiopronin",
    "Belatacept",
    "Everolimus",
    "Perindopril",
    "Ethionamide",
    "Ramipril",
    "Darbepoetin alfa",
    "Ferrous Ammonium Citrate",
    "Basiliximab",
    "Daclizumab",
    "Losartan",
    "Meropenem and Vaborbactam",
    "Allopurinol",
    "Pyrazinamide",
    "Peginesatide",
    "Quinapril",
    "Tamsulosin",
    "Sterile Hemofiltration Hemodiafiltration Solution",
    "Irbesartan",
    "Streptomycin",
    "Rifabutin",
    "Rituximab",
    "Lisinopril",
    "Captopril",
    "Glucarpidase Injection",
    "Isoniazid",
    "Benazepril",
    "Potassium Citrate",
    "Doripenem",
    "Trandolapril",
    "Moexipril HCl Hydrochlorothiazide Tablets",
    "Sirolimus",
    "Morphine",
    "Ethambutol",
    "Enalapril",
    "Muromonab CD 3",
    "Amlodipine",
    "Acetaminophen or Paracetamol",
    "Plazomicin",
    "Iron Dextran",
    "Ciclosporin",
    "Ferrous Fumarate",
    "Hydromorphone",
    "Etelcalcetide",
    "Lymphocyte Immune Globulin-  Anti-thymocyte",
    "Glimepiride",
    "Fosinopril"
  ],
  "Others": [
    "Rifaximin",
    "Terlipressin",
    "Pneumococcal Vaccine Polyvalent",
    "Mometasone Furoate and Formoterol Fumarate",
    "Insulin Detemir",
    "Acebrophylline",
    "Enflurane",
    "Norelgestromin and Ethinyl Estradiol",
    "Felbamate",
    "Cefazolin",
    "Moxidectin",
    "Pinaverium",
    "Icosapent Ethyl",
    "Memantine",
    "Feracrylum",
    "Belladona/Ergotamine/Phenobarbital",
    "Zotepine",
    "Acetaminophen and Codeine",
    "Amyl Nitrite",
    "Eluxadoline",
    "Rimonabant",
    "Erythromycin and Sulfisoxazole",
    "Daclatasvir",
    "Dextroamphetamine",
    "Naproxen",
    "Triamterene",
    "Pamidronate",
    "Alogliptin and Metformin",
    "Terbutaline",
    "Trimethadione",
    "Primaquine",
    "Buspirone",
    "Guaifenesin",
    "Liraglutide [rDNA] Injection",
    "Plecanatide",
    "Valrubicin",
    "Acrivastine and Pseudoephedrine",
    "Ergocalciferol (Vitamin D2)",
    "Citalopram",
    "Propylthiouracil",
    "Nicardipine",
    "Colistimethate Injection",
    "Rolapitant",
    "Cyproheptadine",
    "Etofylline",
    "Glutathione",
    "Tolnaftate",
    "Duloxetine",
    "Ipriflavone",
    "Dexmedetomidine",
    "Micafungin",
    "Abacavir Sulfate, Lamivudine and Zidovudine",
    "Ergotamine Sublingual",
    "Liothyronine",
    "Ethiny- Estradiol- Norethindrone",
    "Dronabinol",
    "Triple Sulfa",
    "Erythropoietin",
    "Etoposide",
    "Ravulizumab",
    "Evolocumab",
    "Vindesine",
    "Felodipine",
    "Mannitol",
    "Allopurinol",
    "Peginterferon Alfa 2 B",
    "Gemfibrozil",
    "Ergotamine Tartrate and Caffeine",
    "Encorafenib",
    "Cenegermin-bkbj",
    "Glatiramer",
    "Neomycin Topical",
    "Choline",
    "Alpha One-proteinase inhibitor",
    "Typhoid Vaccine Live",
    "Cisapride",
    "Etelcalcetide",
    "Selinexor",
    "Mepolizumab",
    "Aminophylline",
    "Oral Iron formulation",
    "Methylprednisolone",
    "Guanabenz",
    "Tetanus Toxoid",
    "Flutamide",
    "Oxtriphylline",
    "Calcium",
    "Reserpine",
    "Gemifloxacin",
    "Dasatinib",
    "Lorazepam",
    "Zonisamide",
    "Pioglitazone",
    "Tigecycline",
    "Mesalamine(Mesalazine)",
    "Miltefosine",
    "Gramicidin",
    "Hydroxocobalamin",
    "Plazomicin",
    "Beclomethasone Dipropionate",
    "Levonorgestrel",
    "Indomethacin",
    "Darifenacin",
    "Glimepiride",
    "Ketotifen",
    "Exenatide",
    "Atropine Sulfate Ophthalmic",
    "Oxymorphone",
    "Tibolone",
    "Chlorthalidone",
    "Articane HCl and Epinephrine Injection",
    "Artesunate",
    "Nalmefene",
    "Talazoparib",
    "Enbucrilate",
    "Nicotine",
    "Captopril",
    "Oxymetazoline",
    "Sulbutiamine",
    "Polidocanol Injection",
    "Mogamulizumab-kpkc",
    "Rivastigmine",
    "Phenytoin",
    "Clemastine",
    "Tetanus-Diphtheria-Acellular Pertussis (Tdap)",
    "Remdesivir",
    "Clozapine",
    "Propofol",
    "Terazosin",
    "Disodium hydrogen citrate",
    "Estrogen and Progestin - Oral Contraceptives",
    "Glyburide",
    "Budesonide",
    "Cefixime",
    "Naloxone",
    "Insulin Glulisine",
    "Phthalylsulfathiazole",
    "Brexpiprazole",
    "Olanzapine",
    "Paclitaxel",
    "Torsemide",
    "Azelaic  Acid",
    "Melphalan",
    "Sildenafil",
    "OnabotulinumtoxinA",
    "Nevirapine",
    "Erythromycin Ethylsuccinate Granules",
    "Nitroglycerin Ointment",
    "Tetrahydrozoline Hcl",
    "Chloral Hydrate",
    "Tramadol",
    "Polymyxin, Bacitracin and Neomycin",
    "Enoxaparin",
    "Eplerenone",
    "Dichlorphenamide",
    "Nizatidine",
    "Levodropropizine",
    "Calcitriol",
    "Spectinomycin",
    "Azathioprine",
    "Lincomycin",
    "Metolazone",
    "Somatropin",
    "Sevoflurane",
    "Linezolid",
    "Itopride",
    "Rotigotine",
    "Amifampridine",
    "Pamabrom",
    "Trazodone",
    "Telaprevir",
    "Doripenem",
    "Co-trimoxazole",
    "Becaplermin",
    "Glecaprevir and Pibrentasvir",
    "Naltrexone",
    "Vigabatrin",
    "Oxaceprol",
    "Besifloxacin Ophthalmic Suspension",
    "Butoconazole",
    "Nebivolol",
    "Copanlisib",
    "Pravastatin",
    "Methotrexate",
    "Piperacillin/Tazobactam",
    "Blinatumomab",
    "Cefepime",
    "Dinoprostone",
    "Emtricitabine- Tenofovir",
    "Sulfamethoxazole",
    "Cyanocobalamin (Vitamin B12)",
    "Methdilazine",
    "Erenumab-aooe",
    "Haemophilus B Conjugate Vaccine",
    "Rifapentine",
    "Eribulin mesylate",
    "Dorzolamide/Timolol",
    "Lansoprazole",
    "Infliximab",
    "Oxyfedrine",
    "Dopamine",
    "Saxagliptin and Metformin",
    "Ansuvimab",
    "Hemin",
    "Oseltamivir",
    "Albuterol and Ipratropium",
    "Methylnaltrexone Bromide",
    "Omeprazole and Domperidone",
    "Amoxicillin and Clavulanate Potassium",
    "Levocabastine",
    "Nitrofurantoin",
    "Sulconazole",
    "Terfenadine",
    "Obinutuzumab",
    "Deferasirox",
    "Delamanid",
    "Capsaicin",
    "Bromhexine",
    "Succimer",
    "Penicillamine",
    "Sulfadimidine",
    "Amlodipine and Valsartan",
    "Repaglinide",
    "Cetrimide",
    "Pilocarpine",
    "Zalcitabine",
    "Prednisolone Acetate (Oral Suspension)",
    "Alfacalcidol",
    "Quetiapine",
    "Trioxsalen",
    "Ornidazole",
    "Fosinopril",
    "Kanamycin",
    "Tacrine",
    "Pentostatin",
    "Tolazamide",
    "Pentoxifylline",
    "Rebamipide",
    "Etonogestrel",
    "Eflornithine",
    "Human Papillomavirus Quadrivalent",
    "Cisplatin",
    "Phylloquinone",
    "Drospirenone and Estradiol",
    "Stavudine",
    "Iloperidone",
    "Testosterone Fortesta",
    "Perphenazine",
    "Sulindac",
    "Urofollitropin",
    "Fesoterodine Fumarate",
    "Clomiphene",
    "Lafutidine",
    "Zolpidem",
    "Benralizumab",
    "Japanese Encephalitis Virus Vaccine",
    "Sumatriptan",
    "Adefovir Dipivoxil",
    "Triprolidine",
    "Paromomycin Sulfate",
    "Delavirdine",
    "Balsalazide",
    "Doxapram",
    "Flucytosine",
    "Belimumab",
    "Levalbuterol HCl",
    "Elagolix",
    "Bevacizumab",
    "Rupatadine",
    "Bivalirudin",
    "Hydrochlorothiazide",
    "Artemether and Lumefantrine",
    "Lidocaine",
    "Methsuximide",
    "Ertugliflozin",
    "Phenelzine",
    "Thiabendazole",
    "Clomethiazole",
    "Moclobemide",
    "Abaloparatide",
    "Nadifloxacin",
    "Imidapril",
    "Cranberry",
    "Flodrocortisone",
    "Uridine triacetate",
    "Oritavancin",
    "Leflunomide",
    "Azelastine and Fluticasone",
    "Mosapride",
    "Ezetimibe and Simvastatin",
    "Molgramostim",
    "Nadolol",
    "Dexmethylphenidate Hcl",
    "Carbimazole",
    "Tamoxifen",
    "Mepenzolate",
    "Timolol Ophthalmic",
    "Thyroid -dessicated",
    "Alglucosidase",
    "Milrinone",
    "Bendamustine hydrochloride",
    "Nintedanib",
    "Nimesulide",
    "Sulfacetamide and Prednisolone",
    "Bambuterol",
    "Thioridazine",
    "Mirabegron",
    "Ciclosporin",
    "Isoproterenol Inhalation",
    "Lisdexamfetamine",
    "Doxylamine",
    "Tizanidine",
    "Omadacycline",
    "Anti-Inhibitor Coagulant Complex- Vapor Heated",
    "Rosuvastatin",
    "DPT- Diphtheria, Tetanus and Pertussis Vaccine",
    "Policosanol",
    "Mizolastine",
    "Fexofenadine",
    "Ursodeoxycholic Acid",
    "Phenylbutazone",
    "Azithromycin",
    "Ritodrine",
    "Dequalinium",
    "Pindolol",
    "Calcium Phosphate",
    "Valacyclovir",
    "Patisiran",
    "Parnaparin",
    "Mepacrine",
    "Osimertinib",
    "Dolutegravir",
    "Agalsidase",
    "Dydrogesterone",
    "Pegaptanib",
    "Carbidopa-Levodopa",
    "Chlordiazepoxide",
    "Ganirelix",
    "Methyclothiazide",
    "Aminolevulinic acid",
    "Carmustine",
    "Mitoxantrone",
    "Tranexamic Acid",
    "Naldemedine",
    "Simethicone",
    "Atracurium",
    "Acrivastine",
    "Ivabradine",
    "Primidone",
    "Ivosidenib",
    "Famotidine and Ibuprofen",
    "Methyldopa",
    "Bleomycin",
    "Lamotrigine",
    "Plerixafor Injection",
    "Insulin Aspart",
    "Timolol Oral",
    "Cephradine",
    "Ibandronate",
    "Panobinostat",
    "Etodolac",
    "Sodium Polystyrene Sulfonate",
    "Cevimeline",
    "Filgrastim",
    "Rabeprazole and Itopride",
    "Amiodarone",
    "Dimethylglycine",
    "Eszopiclone",
    "Dipyridamole",
    "Yohimbine",
    "Choline Magnesium Salicylate",
    "Cephalexin",
    "Levocarnitine",
    "Aceclofenac",
    "Antivenom",
    "Ranitidine",
    "Meperidine",
    "Tocilizumab Injection",
    "Iodine",
    "Insulin Lispro",
    "Buprenorphine",
    "Telavancin",
    "Candesartan",
    "Ardeparin",
    "Tositumomab and Iodine 1131 Tositumomab",
    "Voglibose",
    "Carbachol",
    "Bortezomib",
    "Prothionamide",
    "Suprofen",
    "Eperisone",
    "Sotalol",
    "Procaine- Penicillin",
    "Methylphenidate",
    "Lisinopril",
    "Natamycin",
    "Levothyroxine",
    "Esomeprazole",
    "Metaproterenol / Orciprenaline",
    "Glibenclamide and Metformin",
    "Triazolam",
    "Naloxegol",
    "Stool Softener",
    "Difluprednate Ophthalmic Emulsion",
    "Oxyphenonium",
    "Saxagliptin",
    "Irinotecan",
    "Aspirin and Codeine",
    "Phenoxybenzamine",
    "Furosemide",
    "Sumatriptan Succinate and Naproxen Sodium",
    "Valproic Acid",
    "Nitrazepam",
    "Tretinoin",
    "Mephentermine",
    "Dinutuximab",
    "Tofacitinib",
    "Benazepril",
    "Benzalkonium chloride",
    "Clofibrate",
    "Trabectedin",
    "Niclosamide",
    "Burosumab-twza",
    "Latanoprostene bunod ophthalmic",
    "Cefuroxime axetil",
    "Mephobarbital",
    "Guanethidine Monosulfate",
    "Darunavir",
    "Oxethazaine",
    "Acetylcysteine",
    "Aminocaproic Acid",
    "Naproxen and Esomeprazole Magnesium",
    "Elotuzumab",
    "Bedaquiline",
    "Pramipexole",
    "Ethionamide",
    "Ipilimumab",
    "Ivacaftor",
    "Bupropion",
    "Methohexital",
    "Hydroxyurea",
    "Hydrocodone",
    "Ketorolac",
    "Rabies Vaccine",
    "Carboprost",
    "Camylofin",
    "Disulfiram",
    "Brexanolone",
    "Pentosan Polysulfate Sodium",
    "Alprostadil",
    "Buprenorphine and Naloxone",
    "Regadenoson",
    "Paricalcitol",
    "Suramin",
    "Dimethindene",
    "Isoflurane",
    "Hydroquinone",
    "Moxonidine",
    "Oxymetholone",
    "Adapalene",
    "Zoledronic Acid",
    "Pegvaliase-pqpz",
    "Acebutolol",
    "Mazindol",
    "Glipizide and Metformin",
    "Mesterolone",
    "Sertaconazole Nitrate",
    "Nandrolone",
    "Indapamide",
    "Bitolterol",
    "Tiotropium",
    "Glycopyrrolate",
    "Paliperidone Palmitrate",
    "Metronidazole",
    "Hydroxyapatite",
    "Posaconazole",
    "Olanzapine and Fluoxetine",
    "Acenocoumarol",
    "Amoxapine",
    "Arteether",
    "Stiripentol",
    "Glucosamine",
    "Silymarin",
    "Valsartan",
    "Netarsudil",
    "Colestipol",
    "Amphotericin B",
    "Ipratropium Bromide",
    "Olmesartan",
    "Reviparin Sodium",
    "Benzoyl Peroxide",
    "Rifampin- Isoniazid- Pyrazinamide",
    "Minoxidil Topical",
    "Alprazolam",
    "Bosentan",
    "Clopidogrel",
    "Hamycin",
    "Cytomegalovirus Immune Globulin",
    "Etoricoxib",
    "Pioglitazone and Metformin",
    "Porfimer Sodium",
    "Succinylcholine",
    "Acetaminophen and Oxycodone",
    "Ampicillin and Sulbactam",
    "Metoprolol",
    "Amoxicillin",
    "Tobramycin Ophthalmic",
    "Carbinoxamine",
    "Ibuprofen",
    "Cidofovir",
    "Ribavirin",
    "Rosiglitazone and Metformin",
    "Bemiparin",
    "Bezafibrate",
    "Docosahexaenoic acid",
    "Levobunolol (Ophthalmic)",
    "Leucovorin",
    "Cinacalcet",
    "Ixazomib",
    "Colchicine",
    "Zinc Acetate",
    "Pemirolast Ophthalmic",
    "Triclabendazole",
    "Palonosetron",
    "Daptomycin",
    "Flunarizine",
    "Omalizumab",
    "Interferon Alfacon-1",
    "Suxamethonium Chloride",
    "Acetaminophen or Paracetamol",
    "Chlorzoxazone",
    "Dacarbazine",
    "Raltegravir",
    "Acetazolamide",
    "Pyrazinamide",
    "Arginine",
    "Levodopa",
    "Procyclidine",
    "Estrogen",
    "Ertapenem",
    "Rimantadine",
    "Obiltoxaximab",
    "Cromolyn Sodium Oral Inhalation",
    "Sarilumab",
    "Mebendazole",
    "Cannabidiol",
    "Ezogabine",
    "Albumin Human",
    "Teriparatide",
    "Ephedrine",
    "Raloxifene",
    "Phenindione",
    "Oprelvekin",
    "Norfloxacin",
    "Meningococcal Conjugate Vaccine",
    "Interferon Gamma 1B",
    "Domperidone",
    "Dilazep",
    "Desaminooxytocin",
    "Venlafaxine",
    "Atazanavir",
    "Alglucerase injection",
    "Riluzole",
    "Doxercalciferol",
    "Rituximab",
    "Carfilzomib",
    "Alemtuzumab",
    "Glucagon",
    "Citicoline",
    "Anthrax Vaccine Adsorbed",
    "Vinorelbine Tartrate",
    "Telmisartan",
    "Atropine Ophthalmic",
    "Papaverine",
    "Metyrosine",
    "Theophylline",
    "Sibutramine",
    "Larotrectinib",
    "Nitrendipine",
    "Benazepril HCl and Hydrochlorothiazide",
    "Botulinum Toxin Type A",
    "Metadoxine",
    "Biotin",
    "Abacavir",
    "Naftopidil",
    "Diclofenac",
    "Dexamethasone Ophthalmic- Otic",
    "Prochlorperazine",
    "Ketoconazole",
    "Atenolol",
    "Golimumab",
    "Ceftizoxime",
    "Prazosin",
    "Aspirin and Extended Release Dipyridamole",
    "Epinastine HCl Ophthalmic Solution",
    "Amantadine",
    "Pravastatin Sodium",
    "Psyllium",
    "Fenofibric Acid",
    "Loteprednol",
    "Pancrelipase / Pancreatin",
    "Fluconazole",
    "Bimatoprost",
    "Amoxicillin and Bromhexine",
    "Fostamatinib",
    "Entecavir",
    "Cefoxitin",
    "Acyclovir And Hydrocortisone",
    "Mebeverine",
    "Antihemophiliac factor",
    "Thiothixene",
    "Lamivudine",
    "Xanthinol Nicotinate",
    "Ticarcillin",
    "Isradipine",
    "Telmisartan and Hydrochlorothiazide",
    "Neostigmine",
    "Pefloxacin",
    "Ofloxacin",
    "Cloxacillin",
    "Tenofovir",
    "Colesevelam Hcl",
    "Artemether",
    "Enasidenib",
    "Ramelteon",
    "Revefenacin",
    "Sevelamer",
    "Irbesartan and Hydrochlorothiazide",
    "Phenazone",
    "Guselkumab",
    "Fosamprenavir Calcium",
    "Embramine",
    "Rasagiline",
    "Amoxicillin and Carbocisteine",
    "Rimexolone Ophthalmic",
    "Amitriptyline and Perphenazine",
    "Valdecoxib",
    "Zileuton",
    "Moroctocog Alpha",
    "Abarelix",
    "Belladonna Alkaloid Combinations and Phenobarbital",
    "Vincristine",
    "Eprosartan Mesylate Hydrochlorothiazide",
    "Sulfasalazine",
    "Enalapril",
    "Aducanumab",
    "Epinephrine/ Chlorpheniramine",
    "Cetuximab",
    "Cefoperazone Sodium Injection",
    "Quinine",
    "Mestranol and Norethindrone",
    "Clarithromycin",
    "Brinzolamide",
    "Daclizumab",
    "Prednisone",
    "Adapalene and Benzoyl Peroxide",
    "Ibrutinib",
    "Pregabalin",
    "Pyrimethamine- Sulfadoxine",
    "Technetium Tc 99m Tilmanocept",
    "Chorionic Gonadotropin",
    "Dicloxacillin",
    "Alefacept",
    "Biperiden",
    "Epoetin beta-methoxy polyethylene glycol",
    "Sulphaguanidine",
    "Varenicline",
    "Bromocriptine",
    "Piracetam",
    "Triamcinolone Topical",
    "Sparfloxacin",
    "Fosphenytoin",
    "Tenoxicam",
    "Hydroxy Progesterone",
    "Factor IX",
    "Isocarboxazid",
    "Teniposide",
    "Ifosfamide",
    "Nitroglycerin Skin Patches",
    "Prucalopride",
    "Valethamate",
    "Olaparib",
    "Tafenoquine",
    "Doxepin",
    "Ofatumumab",
    "Cetirizine",
    "Lithium",
    "Ziprasidone",
    "Melitracen",
    "Norepinephrine",
    "Dienestrol",
    "Busulphan",
    "Anthralin",
    "Lisinopril and Hydrochlorothiazide",
    "Chloroquine",
    "Ormeloxifene",
    "Isoetharine",
    "Meningococcal C,Y and Haemophilus B Tetanus Toxoid",
    "Ezetimibe",
    "Topical Clarithromycin",
    "Streptomycin",
    "Codeine",
    "Flumazenil",
    "Tobramycin",
    "Triethanolamine Polypeptide",
    "Neratinib",
    "Ledipasvir and Sofosbuvir",
    "Amphetamine, Dextroamphetamine Mixed Salts",
    "Lomustine",
    "Hylan g-f 20",
    "Aztreonam",
    "Eculizumab",
    "Pramlintide Acetate Injection",
    "Sulfacetamide and Sulfur",
    "Mipomersen Injection",
    "Tyrothricin",
    "Tianeptine",
    "Carboplatin",
    "Homatropine",
    "Omeprazole and Sodium Bicarbonate",
    "Rutin",
    "Labetalol",
    "Fibrinogen Concentrate",
    "Parecoxib",
    "Bulaquine",
    "Peppermint oil",
    "Binimetinib",
    "Hydroxychloroquine",
    "Esmolol",
    "Orlistat",
    "Atezolizumab",
    "Enalapril and Hydrochlorothiazide",
    "Misoprostol",
    "Prazepam",
    "Sofosbuvir",
    "Trolamine Salicylate",
    "Clotrimazole",
    "Isometheptene and Dichloralphenazone and APAP",
    "Balofloxacin",
    "Tolterodine",
    "Velaglucerase Alfa for Injection",
    "L-Ornithine L-Aspartate",
    "Cefadroxil",
    "Triclosan",
    "Calcium Carbonate",
    "Oxandrolone",
    "Diphenylpyraline",
    "Gold Sodium Thiomalate",
    "Morphine",
    "Interferon Beta-1B",
    "Morrhuate Sodium Injection",
    "Macimorelin",
    "Testosterone Cypionate Injection",
    "Mechlorethamine HCl",
    "Lymphocyte Immune Globulin-  Anti-thymocyte",
    "Deutetrabenazine",
    "Tolfenamic Acid",
    "Triamcinolone Hexacetonide",
    "Sodium Oxybate",
    "Teriflunomide",
    "Hydrocodone and Chlorpheniramine",
    "Senna",
    "Cabergoline",
    "Crotamiton",
    "Xylitol",
    "Lucinactant",
    "Ticlopidine",
    "Betrixaban",
    "Salbutamol",
    "Unoprostone",
    "Cefprozil",
    "Praziquantel",
    "Thrombin Topical Bovine Origin",
    "Droxidopa",
    "Migalastat",
    "Orphenadrine",
    "Roxithromycin",
    "Nalidixic Acid",
    "Didanosine",
    "Erdosteine",
    "Dexamethasone Oral",
    "Nafarelin",
    "Dapagliflozin",
    "Rocuronium",
    "Cisatracurium Besylate",
    "Dehydroepiandrosterone",
    "Dipotassium hydrogen citrate",
    "Fluphenazine",
    "Nesiritide",
    "Pediarix Vaccine",
    "Thiopental",
    "Lacosamide",
    "Nitroxazepine",
    "Nelfinavir",
    "Histrelin Acetate",
    "Quinidine",
    "Loxaglate",
    "Baloxavir marboxil",
    "Peginesatide",
    "Lubiprostone",
    "Dehydroemetine",
    "Arformoterol Tartrate Inhalation",
    "Phenacemide",
    "Zaltoprofen",
    "Levocetirizine",
    "Nortriptyline",
    "Piribedil",
    "Flurazepam",
    "Imatinib",
    "Alpha galactosidase",
    "Ketoprofen",
    "Lornoxicam",
    "Eletriptan",
    "Perindopril and Indapamide",
    "Beclomethasone",
    "Lopinavir and Ritonavir",
    "Ceftaroline Fosamil Injection",
    "Zaleplon",
    "Raxibacumab",
    "Clonidine",
    "Nedocromil Inhalation Aerosol",
    "Ceritinib",
    "Interferon Alfa-N3 -Human Leukocyte derived",
    "Chloroxine",
    "Adrenochrome monosemicarbazone / Carbazochrome",
    "Apixaban",
    "Venetoclax",
    "Permethrin",
    "Doxorubicin",
    "Meloxicam",
    "Progesterone",
    "Ketorolac Trometamol Ophthalmic",
    "Alfuzosin",
    "Tesamorelin",
    "Diethylamine Salicylate",
    "Oxprenolol",
    "Promethazine",
    "Dicyclomine",
    "Guanfacine",
    "Emtricitabine- Rilpivirine- Tenofovir",
    "Olaratumab",
    "Bethanechol",
    "Meropenem and Vaborbactam",
    "Clindamycin",
    "Teneligliptin",
    "Siltuximab",
    "Atomoxetine",
    "Isosorbide Dinitrate and Hydralazine",
    "Avatrombopag",
    "Tazarotene",
    "Emtricitabine",
    "Ganirelix Acetate Injection",
    "Cholestyramine Resin",
    "Diclofenac Sodium and Misoprostol",
    "Tiludronate",
    "Adalimumab",
    "Linagliptin and Metformin Hydrochloride",
    "Aldesleukin",
    "Vecuronium",
    "Probucol",
    "Cyclosporine",
    "Gabapentin",
    "Elapegademase-lvlr",
    "Aliskiren and valsartan",
    "Solriamfetol",
    "Hepatitis B (Recombinant) Vaccine",
    "Pomalidomide",
    "Rivaroxaban",
    "Methylergometrine",
    "Tositumomab",
    "Siponimod",
    "Dutasteride",
    "Simvastatin and Sitagliptin",
    "Cyclopentolate",
    "Ibritumomab Tiuxetan",
    "Etidronate",
    "Ferrous Gluconate",
    "Amlodipine and Olmesartan",
    "Degarelix",
    "Phenylephrine",
    "Tegafur, Gimeracil, Oteracil",
    "Phosphocol",
    "Trifluoperazine",
    "Risperidone",
    "Dothiepin",
    "Acamprosate",
    "Etamsylate",
    "Abciximab",
    "Chlorhexidine",
    "Diethylpropion",
    "Vinblastine",
    "Pazufloxacin",
    "Nisoldipine",
    "Dabigatran",
    "High Molecular Weight Hyaluronan",
    "Xylometazoline",
    "Diacerein",
    "Sarecycline",
    "Amlodipine and Lisinopril",
    "Mifepristone",
    "Axicabtagene Ciloleucel",
    "Pimozide",
    "Cinchocaine",
    "Talimogene laherparepvec",
    "Carteolol",
    "Estropipate",
    "Penciclovir",
    "Chlorpheniramine and Phenylpropanolamine",
    "Oxcarbazepine",
    "Vilazodone Hydrochloride",
    "Carbonyl Iron",
    "Ethosuximide",
    "Folic acid",
    "Iloprost",
    "Protriptyline Hydrochloride",
    "Meprobamate and Aspirin",
    "Aliskiren and Amlodipine",
    "Desipramine",
    "Chlorpheniramine",
    "Leuprolide",
    "Benoxinate",
    "Alectinib",
    "Miglitol",
    "Cyclizine",
    "Evening Primrose",
    "Diclofenac Sodium (Topical Solution)",
    "Isoprenaline",
    "Polio vaccines",
    "Ferrous Fumarate",
    "Ramucirumab",
    "Captopril and Hydrochlorothiazide",
    "Isosorbide",
    "Abiraterone Acetate",
    "Trifluperidol",
    "Benidipine",
    "Probenecid and Colchicines",
    "Latanoprost",
    "Desmopressin",
    "Formoterol",
    "Budesonide and Formoterol",
    "Meclofenamate",
    "Noscapine",
    "Loperamide",
    "Oxytetracycline",
    "Danazol",
    "Calfactant",
    "Cholera Vaccine",
    "Iron Sucrose",
    "Abatacept",
    "Idelalisib",
    "Reslizumab",
    "Amoxicillin and Clavulanic acid",
    "Aprotinin",
    "Griseofulvin",
    "Topiramate",
    "Zinc Pyrithione",
    "Drug Sodium Iodide-i-131",
    "Oxybutynin Hydrochloride",
    "Ondansetron",
    "Fosnetupitant and Palonosetron",
    "Disodium Edetate",
    "Diclofenac Sodium Ophthalmic Solution",
    "Anagrelide",
    "Tapentadol",
    "Ibutilide",
    "Liotrix",
    "Sitagliptin",
    "Ponatinib",
    "Tamsulosin",
    "Terbinafine",
    "Iron - III Hydroxide Polymaltose Complex - IPC",
    "Ciclesonide",
    "Selegiline",
    "Benzoyl Peroxide and Clindamycin Phosphate",
    "Norethindrone",
    "Gemcitabine",
    "Brimonidine",
    "Pimavanserin",
    "Fluoxetine",
    "Voriconazole",
    "Hydrocortisone",
    "Mesna",
    "Carbazochrome",
    "Metamizole",
    "Ethacrynic Acid",
    "Prednisolone Ophthalmic",
    "Azilsartan medoxomil",
    "Pentetate Calcium Trisodium Inj",
    "Ambenonium",
    "Salmeterol",
    "Perindopril",
    "Aluminum Hydroxide and Magnesium Hydroxide",
    "Delafloxacin",
    "Methyltestosterone",
    "Oxiconazole",
    "Tdap",
    "Tolbutamide",
    "Diflunisal",
    "Furazolidone",
    "Lindane",
    "Bacampicillin",
    "Carvedilol",
    "Amlodipine and Losartan",
    "Sirolimus",
    "Lovastatin",
    "Pyridoxine",
    "Ethoheptazine",
    "Lynestrenol",
    "Urokinase",
    "Pitofenone",
    "Verteporfin",
    "Cilostazol",
    "Methylhesperidin",
    "Bisoprolol",
    "Ursodiol",
    "Aliskiren",
    "Emicizumab",
    "Eprosartan",
    "Miconazole",
    "Erythrityl Tetranitrate",
    "Omeprazole",
    "Cefaclor",
    "Dimenhydrinate",
    "Caffeine",
    "Reboxetine",
    "Ranolazine",
    "Lurasidone",
    "Omacetaxine Mepesuccinate",
    "Clonazepam",
    "Mexiletine",
    "Diltiazem",
    "Fingolimod",
    "Eliglustat",
    "Amlodipine",
    "Tioconazole",
    "Peramivir",
    "Cholecalciferol",
    "Melatonin",
    "Paroxetine",
    "Metformin",
    "Asenapine",
    "Alcaftadine Ophthalmic Solution",
    "Caspofungin",
    "Vedolizumab",
    "Naphazoline",
    "Nateglinide",
    "Pitolisant",
    "Sodium zirconium cyclosilicate",
    "Terconazole",
    "Mepivacaine",
    "Rilpivirine",
    "Angiotensin II",
    "Palivizumab",
    "Propafenone",
    "Triptorelin",
    "Spiramycin",
    "Famciclovir",
    "Procarbazine",
    "Eicosapentaenoic acid",
    "Interferon Alfa  2A",
    "Ethacridine",
    "Indinavir",
    "Clindamycin and Tretinoin",
    "Disopyramide",
    "Trospium Chloride",
    "Thalidomide",
    "Quinupristin and Dalfopristin",
    "Rifampin",
    "Daunorubicin",
    "Dutasteride And Tamsulosin",
    "Pantoprazole",
    "Naproxen- Lansoprazole",
    "Ozagrel",
    "Demecarium",
    "Everolimus",
    "Bosutinib",
    "Cyclobenzaprine",
    "Ritonavir",
    "Docusate",
    "Quinapril",
    "Flecainide",
    "Methamphetamine",
    "Dexrabeprazole Sodium",
    "Chloramphenicol",
    "Meprobamate",
    "Ergometrine",
    "Cefetamet",
    "Interferon Alpha- Two B",
    "Cytarabine",
    "Vestronidase Alfa",
    "Thymoglobulin",
    "Pralidoxime",
    "Risedronate",
    "Sargramostim",
    "Meropenem",
    "Lacidipine",
    "Methysergide",
    "Diloxanide",
    "Sermoline Acetate",
    "Canagliflozin",
    "Pirbuterol Acetate",
    "Clioquinol",
    "Carbamazepine",
    "Bacitracin (Neomycin/Polymyxin B) Ophthalmic",
    "Baclofen",
    "Interferon Alfa-2b and Ribavirin",
    "Verapamil",
    "Aliskiren and hydrochlorothiazide",
    "Fluoxetine and Olanzapine",
    "Denosumab",
    "Albendazole",
    "Testosterone Enanthate",
    "Calamine Lotion",
    "Hydromorphone",
    "Dantrolene",
    "Segesterone Acetate and Ethinyl Estradiol",
    "Suvorexant",
    "Amiloride and Hydrochlorothiazide",
    "Isoniazid",
    "Emedastine Difumarate Ophthalmic Solution",
    "Desogestrel and Ethinyl Estradiol",
    "Octreotide",
    "Levosulpiride",
    "Butenafine",
    "Doravirine",
    "Travoprost",
    "Salmeterol and Fluticasone",
    "Yellow Fever Vaccine",
    "Econazole",
    "Pitavastatin",
    "Anakinra",
    "Dimercaprol",
    "Diphenhydramine",
    "Irbesartan",
    "Faropenem",
    "Carbenicillin",
    "Danaparoid",
    "Halothane",
    "Etravirine",
    "Ciclopirox",
    "Allylestrenol",
    "Butorphanol",
    "Monobenzone",
    "Finafloxacin",
    "Clevidipine",
    "Glucomannan",
    "Apraclonidine",
    "Niraparib",
    "Docosanol",
    "Mianserin",
    "Ocrelizumab",
    "Desloratadine",
    "Heparin",
    "Magaldrate-Simethicone",
    "Haemophilus B Conjugate and Hepatitis B Vaccine",
    "Dalfampridine",
    "Benztropine",
    "Diethylstilbestrol",
    "Fludarabine",
    "Midodrine",
    "Pemetrexed",
    "Ropinirole",
    "Buclizine",
    "Rapacuronium",
    "Epalrestat",
    "Cefotaxime",
    "Pegvisomant",
    "Pentamidine",
    "Vardenafil",
    "Roxatidine",
    "Nefopam",
    "Moxifloxacin",
    "Riboflavin (Vitamin B2)",
    "Ketamine",
    "Clomipramine",
    "Immune Globulin Intravenous",
    "Tolcapone",
    "Mechlorethamine",
    "Frovatriptan",
    "Amobarbital",
    "Intrauterine Copper Contraceptive",
    "Doxycycline",
    "Candesartan cilexetil and Hydrochlorothiazide",
    "Sertraline",
    "Telmisartan and Amlodipine",
    "Cefamandole",
    "Tinzaparin",
    "Indacaterol",
    "Safinamide",
    "Phentolamine Mesylate",
    "Prenoxdiazine",
    "Methimazole",
    "Measles, Mumps and Rubella (MMR) vaccine",
    "Quinapril HC- Hydrochlorothiazide Tablets",
    "Mefloquine",
    "Potassium Citrate",
    "Roflumilast",
    "Dabrafenib",
    "Medrysone  Liquifilm Ophthalmic",
    "Thymalfasin",
    "Ceftibuten",
    "Capreomycin",
    "Choline Magnesium Trisalicylate",
    "Olopatadine",
    "Troxipide",
    "Iron Dextran",
    "Imiglucerase",
    "Ropivacaine",
    "Secobarbital",
    "Nusinersen",
    "Amorolfine",
    "Oxacillin  Injection",
    "Methionine",
    "Bumetanide",
    "Dexlansoprazole",
    "Sofosbuvir, Velpatasvir, and Voxilaprevir",
    "Fluticasone",
    "Trametinib",
    "Benzocaine",
    "Menotropins",
    "Etanercept",
    "Gatifloxacin",
    "Argatroban",
    "Lamivudine- Zidovudine",
    "Echothiophate",
    "Vancomycin",
    "Trandolapril- Verapamil",
    "Alclometasone Dipropionate",
    "Hydrochlorothiazide and Triamterene",
    "Pemoline",
    "Dimethicone",
    "Hydralazine",
    "Encainide Hydrochloride",
    "Sultamicillin",
    "Oxaprozin",
    "Pipecuronium",
    "Maraviroc",
    "Ceftriaxone",
    "Bisacodyl",
    "Nitazoxanide",
    "Repaglinide and Metformin",
    "Aliskiren, Amlodipine and Hydrochlorothiazide",
    "Ciprofloxacin and Tinidazole",
    "Moricizine",
    "Mometasone",
    "Ferrous Ammonium Citrate",
    "Hydrotalcite",
    "Atorvastatin",
    "Mecamylamine",
    "Cyproterone Tablet",
    "Secnidazole",
    "Insulin",
    "Acyclovir",
    "Hydrochlorothiazide and Spironolactone",
    "Alpha-linolenic acid",
    "Rufinamide",
    "Propranolol",
    "Hemophilus B",
    "Loxapine",
    "Pegfilgrastim",
    "Inotersen",
    "Rabeprazole",
    "Imipramine",
    "Nefazodone",
    "Xipamide",
    "Nimotuzumab",
    "Norgestimate and Ethinyl Estradiol",
    "Boceprevir",
    "Sodium Tetradecyl",
    "Inotuzumab ozogamicin",
    "Glibenclamide",
    "Plicamycin",
    "Tecovirimat",
    "Phenazopyridine",
    "Insoluble Prussian Blue",
    "Baricitinib",
    "Nabumetone",
    "Atenolol and Chlorthalidone",
    "Pegloticase",
    "Proguanil",
    "Amitriptyline",
    "Mitomycin",
    "Apomorphine",
    "Metaxalone",
    "Mecobalamin",
    "Diazepam",
    "Levetiracetam",
    "Chlorambucil",
    "Penicillin v Potassium",
    "Azelastine",
    "Ebastine",
    "Alogliptin",
    "Lomefloxacin",
    "Ampenavir",
    "Zanamivir",
    "Almotriptan",
    "Ceftazidime",
    "Chondroitin",
    "Abacavir Sulfate and Lamivudine",
    "Pentobarbital",
    "Cyclophosphamide",
    "Dipivefrin Ophthalmic",
    "Benzonatate",
    "Gentamicin Ophthalmic",
    "Betaxolol Ophthalmic",
    "Metoclopramide",
    "Zuclopenthixol",
    "Darbepoetin alfa",
    "Polifeprosan 20 with Carmustine",
    "Chlorpropamide",
    "Trimeprazine",
    "Erythromycin",
    "Zopiclone",
    "Autologous Cultured Chondrocytes",
    "Ferric maltol",
    "Idarubicin",
    "Sufentanil Citrate Injection",
    "Desflurane",
    "Flosequinan",
    "Megestrol",
    "Alogliptin and Pioglitazone",
    "Chlorpheniramine and Hydrocodone",
    "Ethinyl Estradiol and Levonorgestrel",
    "Sulfacetamide Ophthalmic",
    "Fluvoxamine",
    "Tafluprost",
    "Secukinumab",
    "Alteplase",
    "Aripiprazole",
    "Pseudoephedrine and Triprolidine",
    "Telbivudine",
    "Dalteparin",
    "Streptokinase",
    "Pentazocine and Naloxone",
    "Divalproex",
    "Betamethasone Ophthalmic",
    "Naratriptan",
    "Ranibizumab",
    "Simeprevir",
    "Dexamethasone Intravitreal Implant",
    "Drotaverine",
    "Acitretin",
    "Stanozolol",
    "Niacin",
    "Nitroglycerin Tablets, Capsules and Spray",
    "Aclidinium Bromide Oral Inhalation",
    "Lercanidipine",
    "Amisulpride",
    "Acetaminophen, Butalbital and Caffeine",
    "Fosfomycin",
    "Ethambutol",
    "Lepirudin",
    "Luliconazole",
    "Epinephrine",
    "Ambroxol",
    "Dobutamine",
    "Oxycodone Hydrochloride",
    "Ferrous Sulfate - Iron",
    "Triamcinolone Inhalation",
    "Lusutrombopag",
    "Phendimetrazine Tartrate",
    "Auranofin",
    "Linaclotide",
    "Trifluridine",
    "Valsartan and Hydrochlorothiazide",
    "Linagliptin",
    "Telotristat ethyl",
    "Chlorpromazine",
    "Famotidine",
    "Chlorothiazide",
    "Mefenamic Acid",
    "Flunisolide",
    "Flupenthixol",
    "Lanreotide",
    "Butabarbital",
    "Pegaspargase",
    "Zidovudine",
    "Trihexyphenidyl",
    "Tetracycline",
    "Tinidazole",
    "Goserelin",
    "Tegafur and Uracil",
    "Zolmitriptan",
    "Psoralen (PUVA)",
    "Hydroxyzine",
    "Pyridostigmine",
    "Hydrocortisone Valerate",
    "Hydroflumethiazide",
    "Donepezil",
    "Naphazoline/ Pheniramine - Ophthalmic",
    "Sulfinpyrazone",
    "Brivaracetam",
    "Gensparin",
    "Respiratory Syncitial Virus Immune Globulin",
    "Cobicistat-Elvitegravir-Emtricitabine-Tenofovir",
    "Cromolyn Sodium Nasal Solution",
    "Simvastatin",
    "Nabilone",
    "Fosfestrol",
    "Efavirenz",
    "Avapritinib",
    "Tacrolimus",
    "Tiagabine",
    "Haloperidol",
    "Etizolam",
    "Vasopressin",
    "Moxetumomab pasudotox-tdfk",
    "Lodoxamide Tromethamine",
    "Escitalopram",
    "Ferumoxytol",
    "Capecitabine",
    "Oxazepam",
    "Epirubicin",
    "Nystatin",
    "Ganciclovir",
    "Ethotoin",
    "Pembrolizumab",
    "Zoster Vaccine Live",
    "Imipenem and Cilastatin",
    "Magnesium sulphate",
    "Flavoxate",
    "Alendronate",
    "Minoxidil oral",
    "Corticotropin",
    "Digoxin",
    "Galantamine",
    "Acetaminophen and Hydrocodone Bitartrate",
    "Interferon Beta 1A",
    "Acarbose",
    "Dextran",
    "Perampanel",
    "Temozolomide",
    "Ticagrelor",
    "Olmesartan Medoxomil and Hydrochlorothiazide",
    "Cerliponase alfa",
    "Milnacipran Hcl",
    "Granisetron",
    "Methenamine Hippurate",
    "Entacapone",
    "Solifenacin",
    "Dulaglutide",
    "Nivolumab",
    "Lactulose",
    "Celecoxib",
    "Fluorometholone",
    "Niacin Er and Simvastatin",
    "Penfluridol",
    "Nicorandil",
    "Denileukin Diftitox",
    "Loratadine",
    "Medroxyprogesterone",
    "Semaglutide",
    "Alfentanil Hydrochloride Injection",
    "Cycloserine",
    "Aspirin, Butalbital and Caffeine",
    "Hepatitis A Vaccine",
    "Itraconazole",
    "Moexipril HCl Hydrochlorothiazide Tablets",
    "Procainamide",
    "Muromonab CD 3",
    "Oxytocin",
    "Anti-Inhibitor Coagulant Complex- Heat Treated",
    "Grepafloxacin",
    "Rotavirus Vaccine",
    "Brompheniramine",
    "Hydrocortisone, Neomycin and Polymyxin",
    "Acalabrutinib",
    "Cimetidine",
    "Finasteride",
    "Duvelisib",
    "Diphenidol",
    "Ambrisentan",
    "Hyoscine",
    "Lidocaine and Prilocaine",
    "Benznidazole",
    "Acetaminophen and Propoxyphene",
    "Probenecid",
    "Amlodipine and Enalapril",
    "Isotretinoin",
    "Alclometasone",
    "Idoxuridine Ophthalmic",
    "Chlorpheniramine- Hydrocodone- Pseudoephedrine",
    "Lenalidomide",
    "Ampicillin",
    "Benzphetamine",
    "Calcitonin- Salmon",
    "Framycetin",
    "Revaprazan",
    "Meclizine",
    "Moexipril Hydrochloride",
    "Tinocordin",
    "Certolizumab",
    "Levofloxacin",
    "Ciprofloxacin",
    "Pirenzepine",
    "Ergoloid Mesylates",
    "Doxazosin",
    "Abobotulinumtoxin A Injection",
    "Mecasermin [rDNA origin] Injection",
    "Bepotastine",
    "Basiliximab",
    "Losartan",
    "Methocarbamol",
    "Vortioxetine",
    "Bretylium Tosylate Injection",
    "Cefotetan",
    "L-methylfolate",
    "Ivermectin",
    "Somatrem",
    "Nadroparin",
    "Methazolamide",
    "Taliglucerase Alfa",
    "Armodafinil",
    "Doxofylline",
    "Fondaparinux",
    "Deferiprone",
    "Montelukast",
    "Pilocarpine Ophthalmic",
    "Astemizole",
    "Natalizumab",
    "Tranylcypromine",
    "Multivitamin",
    "Thyroxine",
    "Furosemide and Amiloride",
    "Fremanezumab-vfrm",
    "Pantoprazole and Domperidone",
    "Pethidine",
    "Cariprazine",
    "Methenamine",
    "Trientine",
    "Diethylcarbamazine",
    "Omega 3-acid Ethyl Esters",
    "Nifedipine",
    "Morphine Sulfate and Naltrexone Hydrochloride",
    "Sumatriptan Transdermal System (TDS)",
    "Nimodipine",
    "Satranidazole",
    "Cephaloridine",
    "Modafinil",
    "Avelumab",
    "Lofexidine",
    "Piperazine",
    "Gabapentin Enacarbil",
    "Acetohexamide",
    "Nilutamide",
    "Testosterone",
    "Febuxostat",
    "Clofazimine",
    "Caplacizumab-yhdp",
    "Dactinomycin",
    "Olsalazine",
    "Clorazepate",
    "Tryptophan",
    "Clove oil",
    "Astaxanthin",
    "Citric acid and Sodium Citrate",
    "Midostaurin",
    "Bupivacaine",
    "Maprotiline",
    "Lutetium Lu 177 dotatate",
    "Albuterol (Salbutamol)",
    "Isopropamide",
    "Sofosbuvir and Velpatasvir",
    "Vitamin E ( alpha Tocopherol )",
    "Trimetazidine Hydrochloride",
    "Desvenlafaxine",
    "Sertaconazole",
    "Triamcinolone",
    "Apalutamide",
    "Bifonazole",
    "Nepafenac Ophthalmic",
    "Poractant Alfa",
    "Caprylidene",
    "Cefditoren",
    "Tadalafil",
    "Pseudoephedrine",
    "Propyphenazone",
    "Propantheline",
    "Brentuximab Vedotin",
    "Valbenazine",
    "Typhoid Vi Polysaccharide Vaccine",
    "Mycophenolate Mofetil",
    "Salsalate",
    "Avanafil",
    "Lorcaserin",
    "Thyroglobulin",
    "Methadone",
    "Rizatriptan",
    "Imiquimod",
    "Edrophonium Injection",
    "Aspirin",
    "Clobazam",
    "Bictegravir, Emtricitabine, and Tenofovir Alafenamide",
    "Beractant",
    "Ragweed",
    "Phentermine",
    "Tolmetin",
    "Piroxicam",
    "Minocycline",
    "Amlodipine and Benazepril",
    "Adenosylcobalamin",
    "Azilsartan Medoxomil and Chlorthalidone",
    "Tipranavir",
    "Dimethyl Fumarate",
    "Trimethoprim",
    "Amiloride",
    "Sulfisoxazole",
    "Betahistine",
    "Amikacin",
    "Fenoldopam Mesylate",
    "Benfotiamine",
    "Physostigmine",
    "BCG live  - Bacillus Calmette- Guerin",
    "Edaravone",
    "Lanadelumab-flyo",
    "Vinflunine",
    "Trandolapril",
    "Tetrabenazine",
    "Sisomicin",
    "Chlordiazepoxide and Clidinium Bromide",
    "Ubiquinone / Coenzyme Q10",
    "Flupirtine",
    "Spironolactone",
    "Fluvastatin",
    "Insulin glargine",
    "Lactobacillus acidophilus",
    "Paracetamol",
    "Phenobarbitone",
    "Vildagliptin",
    "Magnesium Hydroxide",
    "Miglustat",
    "Flurbiprofen",
    "Terizidone",
    "Sodium Picosulphate",
    "Treprostinil",
    "Atovaquone",
    "Prep Kit  for Technetium Tc99 Sestamibi",
    "Deferoxamine",
    "Tezacaftor and Ivacaftor",
    "Amlodipine, Valsartan and Hydrochlorothiazide",
    "Sucralfate",
    "Silodosin",
    "Cilnidipine",
    "Lenograstim",
    "Letermovir",
    "Ustekinumab",
    "Aspirin and Oxycodone",
    "Gliclazide",
    "Celiprolol",
    "Phenobarbital",
    "Bicalutamide",
    "Mirtazapine",
    "Desirudin",
    "Glipizide",
    "Galcanezumab-gnlm",
    "Dexibuprofen",
    "Cefdinir",
    "Warfarin",
    "Epoprostenol",
    "Midazolam",
    "Chlorotrianisene",
    "Fenoprofen",
    "Zafirlukast",
    "Garenoxacin Mesylate",
    "Hyoscyamine",
    "Gentamicin",
    "Carisoprodol",
    "Pirfenidone",
    "Ademetionine",
    "Lanthanum Carbonate",
    "Benzydamine",
    "Temazepam",
    "Etynodiol",
    "Fenoverine"
  ]
}
